Update install_dependencies.yml

diff --git a/.github/workflows/install_dependencies.yml b/.github/workflows/install_dependencies.yml
--- a/.github/workflows/install_dependencies.yml
+++ b/.github/workflows/install_dependencies.yml
@@ -11,6 +11,23 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Cache node modules
+        uses: actions/cache@v3
+        with:
+          path: node_modules
+          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-node-
+
       - name: Install Prettier and XML Plugin
         run: |
-          npm install --save-dev prettier @prettier/plugin-xml || { echo "Failed to install Prettier"; exit 1; }
+          if [ ! -d "node_modules" ]; then
+            npm install --save-dev prettier @prettier/plugin-xml || { echo "Failed to install Prettier"; exit 1; }
+          else
+            echo "Dependencies already installed."
+          fi
+
+
+      - name: List installed packages
+        run: npm list --depth=0
+
